version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  ui:
    build: .
    ports:
      - "8501:8501"
    command: streamlit run ui.py
