services:
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    working_dir: /app

  ui:
    build: .
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    command: streamlit run ui.py
    working_dir: /app
